### ISSUE TITLE
Add a hex sticker

### ISSUE THREAD

**Issue by MichaelChirico** [MichaelChirico/potools#206]
My go-to is to incorporate a potoo somehow. I mean look at this fella:

![image](https://user-images.githubusercontent.com/7606389/125176061-66692980-e185-11eb-8880-86cab5b33ce0.png)

**Comment by MichaelChirico** [comment]
Alternatively it could incorporate the po river... Something like this across the background maybe?

![image](https://user-images.githubusercontent.com/7606389/125250324-f2c13c80-e2aa-11eb-8685-38b111ca2995.png)

**Comment by hadley** [comment]
@allisonhorst very kindly drew up this logo. If it looks good to you, I'll do a PR.

![potools_hex](https://user-images.githubusercontent.com/4196/140181397-cf0496e6-103f-44bf-9c9a-ec468f84df9d.png)

**Comment by MichaelChirico** [comment]
may as well CC @eliocamp to make it feel like there's more consensus :)

**Comment by eliocamp** [comment]
Look at that charming fella! So photogenic. <3

**Comment by MichaelChirico** [comment]
the ayes have it :)

PR more than welcome!
