### ISSUE TITLE
translate_package(): How to detect own utility functions, e.g. stopf(...) short for stop(gettextf(...))?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MichaelChirico/potools#223]
Hi, I use internal utility functions like:

```r
stopf <- function(fmt, ..., call. = TRUE, domain = NA) {
  stop(gettextf(fmt, ...), call. = call., domain = domain)
}

warnf <- function(fmt, ..., call. = TRUE, immediate. = FALSE, domain = NA) {
  warning(gettextf(fmt, ...), call. = call., immediate. = immediate., domain = domain)
}
```

so that I can write:

```r
if (x < 0) stopf("Argument 'x' must not be negative: %d", x)
if (length(y) != 1) warnf("Argument 'y' must be of length one: %d", length(y))
```

Is it possible to have `potools::translate_package()` detect these calls and produce pot entries for them?

**Comment by HenrikBengtsson** [comment]
Thank you both.  Using:

```r
res <- potools::translate_package(custom_translation_functions = list(R = "stopf:fmt|1"))
```

works great.  

> ... Let me know if the write-up here needs improvement: ...

The `?potools::translate_package` page LGTM.  But, assuming most people with use `translate_package()` and not `get_message_data()` [correct?], I think it would help if the [README.md](https://github.com/MichaelChirico/potools#customized-translators) would use `translate_package()` instead of `get_message_data()` for the example.

**Comment by hadley** [comment]
`stopf()` and `warningf()` are now handled automatically by `po_extract()`, so I think this can be closed.
