### ISSUE TITLE
Advice for translating collapsed lists?

### ISSUE THREAD

**Issue by hadley** [MichaelChirico/potools#233]
How should I translate code like this?

```R
paste0("Source: " , paste(links, collapse = ", "))
```

I can translate just the `Source`, but presumably languages have different conventions for this. 

Also worth considering `glue::glue_collapse()` or similar, which can generate phrases like `"a, b, c, and d"`

**Comment by hadley** [comment]
I [asked on twitter](https://twitter.com/hadleywickham/status/1455879305406320642?s=20) to get a sense for how this differs. Here's a summary:

* For European languages, the "a, b, {or} c" form is common, but languages other than English don't seem to use the Oxford comma
* In [Japanese](https://twitter.com/yutannihilat_en/status/1455891768407298057?s=20) the conjunction comes first: `(aやb、c)` = `a {or} b, c` 
* In [Spanish](https://twitter.com/julian_urbano/status/1455888999835475977?s=20) the conjunction differs depending on the context ("o", "u", or "ó")

**Comment by hadley** [comment]
Comprehensive solution at https://github.com/rossellhayes/and

**Comment by MichaelChirico** [comment]
Looks great to be able to offload this to `and`. Should that be functionality in `glue`, though?

**Comment by hadley** [comment]
Yeah, I think it would make sense to either bundle the functionality with glue or with potools. It would be useful to have all translation related stuff in one place, but bundling it with potools would imply some packages would need to take a run-time dependency on potools and I don't know how you feel about that.

**Comment by MichaelChirico** [comment]
Right... it looks like `and` is more of a "recommended package" from potools perspective. With `gettextf()` potools would be basically agnostic to it:

```
gettextf("Valid arguments are: %s", toString(valid_args))
# vs
gettext(glue("Valid arguments are: {glue_collapse(valid_args)}"))
# vs
gettext(glue("Valid arguments are: {and(valid_args)}"))
```

So as I'm seeing it now, this could be Suggested & included in vignettes

**Comment by hadley** [comment]
Yeah good point. I'll leave this open to include in my vignette, but otherwise seems like there's nothing for potools to do.

**Comment by hadley** [comment]
Would have to think through the consequences of routinely using `and()` in glue strings; it would be weird to see `Valid arguments are aやb、c` if the rest of the string hasn't been translated.

**Comment by MichaelChirico** [comment]
Agreed... looks like, even for `glue`, the best approach is to recommend it (maybe in the `glue_collapse()` docs)
