### ISSUE TITLE
Upgrade suite to use testthat 3.0

### ISSUE THREAD

**Issue by MichaelChirico** [MichaelChirico/potools#249]
Would probably also benefit a lot from using snapshot tests to handle all the output-related stuff

**Comment by hadley** [comment]
What do you think about also defaulting to `verbose = !is_testing()`? That's a pattern we've started to use, and it seems to make life a little less complicated.

```R
is_testing <- function() {
    identical(Sys.getenv("TESTTHAT"), "true")
}
```

Otherwise, it doesn't look like any changes are needed for 3e.

**Comment by MichaelChirico** [comment]
SGTM! Thanks. I'll also take a pass at moving `expect_equal()` --> `expect_identical()`
