### ISSUE TITLE
mock translations for nonstandard functions

### ISSUE THREAD

**Issue by MichaelChirico** [MichaelChirico/potools#25]
e.g. it seems `tidyverse` favors `rlang::{abort,warn,inform}`. We could supply a tool `create_mock_translations(call)` which (1) finds usages of `call`(s) in the package and (2) creates a file `mock-translations.R` with dummied up versions of `gettext`, e.g.

```
# R/foo.R
rlang::abort("Call failed. Try again")
```

Running `create_mock_translations` creates:

```
# R/mock-translations.R
gettext("Call failed. Try again")
```

This is enough to get the strings into the `.pot` template; ideally it's enough to get it translated as well, but this might require adding a `domain` argument to the calls.

**Comment by MichaelChirico** [comment]
Check: can we just put the strings from these nonstandard calls into the `po` file?

e.g. could we create a wrapper like:

```
stopf <- function(fmt, ..., call. = TRUE, domain = NULL) {
  stop(domain = NA, gettextf(fmt, ..., domain = domain), call. = call.)
}
```

Then only have calls to `stopf()`, and have `translate_package` just know (or be told) to extract strings from `stopf()` calls just as it does for `stop()`/`gettextf()` by default?

**Comment by MichaelChirico** [comment]
It seems like it won't be possible. `tools::xgettext` in trying to find strings runs the following:

```
match.call(gettextf, substitute(gettextf(fmt, ..., domain = domain)))
```

Which errors:

```
Error in match.call(gettextf, substitute(gettextf(fmt, ..., domain = domain))) : 
  ... used in a situation where it does not exist
```

**Comment by MichaelChirico** [comment]
Filed a bug: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=18091

**Comment by mattdowle** [comment]
I don't fully follow how the translations work yet, but all I can say is that even if that R bug is agreed as a bug and fixed, we still couldn't make use of it for several/many years as it would involve updating data.table's R dependency to whenever that fix is released.  So we'd need to find another approach that works in R 3.1+.

**Comment by MichaelChirico** [comment]
IINM it wouldn't be a dependency for the package on CRAN, just a dependency on the R version used in the deployment process.

**Comment by mattdowle** [comment]
In that case, it sounds fine then.  That just leaves the fix being available in R then to use in deployment.
In the meantime,  would this help ...
```
stop <- function(...) .Call("CourStop", ...)
```

**Comment by MichaelChirico** [comment]
The goal for `potools` is to be able to extract strings from user-specified functions to be marked for translation. This will be required for adoption in `rlang` & downstreams which use `rlang::abort`, e.g.

**Comment by mattdowle** [comment]
Related https://github.com/Rdatatable/data.table/pull/4151
