### ISSUE TITLE
Re: alternative software in README.md

### ISSUE THREAD

**Issue by leofontenelle** [MichaelChirico/potools#308]
Both Virtaal and Pootle use the "Localization Toolkit" (aka `translate-toolkit`) behind the hood. I'm told Weblate uses it, too.

**Comment by MichaelChirico** [comment]
Indeed, it certainly seems so!

https://github.com/WeblateOrg/weblate/blob/74183a7046e78fe1dc5d2017263321ab5cecebe0/requirements.txt#L50

Would you like to propose an edit that does justice to the underlying importance of `translate-toolkit`?

**Comment by leofontenelle** [comment]
OK!

*Leonardo Ferreira Fontenelle*
Lattes <https://lattes.cnpq.br/9234772336296638> · ORCID <https://orcid.org/0000-0003-4064-433X> · Mastodon ***@***.***>


Em Dom 5 nov. 2023, às 14:56, Michael Chirico escreveu:

**Comment by leofontenelle** [comment]
By the way, nice explanation of how translations work, for both the developers and the translators! One of the most succinct and clear ones I saw with this scope.

*Leonardo Ferreira Fontenelle*
Lattes <https://lattes.cnpq.br/9234772336296638> · ORCID <https://orcid.org/0000-0003-4064-433X> · Mastodon ***@***.***>


Em Dom 5 nov. 2023, às 16:02, Leonardo Fontenelle escreveu:

**Comment by MichaelChirico** [comment]
Looks like the note in #309 didn't automatically close this; doing so now
